id: I448348FB
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T20:37:43+00:00'
last_modified: '2022-06-08T03:08:19.336821+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS15812
  title: རྟ་ཚག་རྗེ་དྲུང་ངག་དབང་དཔལ་ལྡན་ཆོས་ཀྱི་རྒྱལ་མཚན་གྱི་རྣམ་ཐར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    632D:
      image_group_id: I8LS15817
      title: ''
      total_pages: 121
      order: 1
      base_file: 632D.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
